### ISSUE TITLE
notification text is misleading

### ISSUE THREAD

**Issue by tatankat** [igorlogius/dontLoadImages#2]
Hi,
Thanks for the quick solution! I think the notification is a good idea to inform the user about the effect.
But as a user, I was expecting to read the effect of adding or removing had. So at first glance, I thought the message was about newly opened tabs. Maybe it should mention the need to refresh in the positive way, like (depending on the selection):
> removed/added "\<domain\>" from/to black/whitelist
> refreshed and new pages with this origin will [not] show images

Also, remark that I use the name "pages" (although there should be a better description than "refreshed and new pages" - "reloaded pages" maybe?) as open tabs are in fact affected. So the current notification is wrong. Loading images will change after a reload in the open tabs.

Another small remark: the permissions are not updated in the addon description.
Just another idea: it should be possible make the notification permission optional

**Comment by igorlogius** [comment]
I'll try to improve the tests with your suggestions 
and check if the notification permission can be made optional without breaking anything.

**Comment by igorlogius** [comment]
It seems that if i "just" make the notification permission optional it will be disabled after installation. 
Since the notificaitons are mostly for users which are unfamiliar with the addon, this is a bit problematic.   
So for now i think I'll keep the notification permission as non optional. 

I'll open another  seperate issue to for this.
